version : '3'

services:
  daw-interactive:
    container_name: usaturn/daw-open-api:latest
    build:
      context: .
    environment:
      - SHELL=/bin/bash
    ports:
      - 51337:1337
#    volumes:
#      - ./:/app

    #command: [nginx-debug, '-g', 'daemon off;']
